name: Push to server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0

    - name: Setup SSH
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-host: ${{ secrets.SERVER_ADDRESS }}
        ssh-port: ${{ secrets.SERVER_PORT }}

    - name: Push to server
      run: git remote add server ${{ secrets.GIT_URL }} && git push server main
